const data = {
    products: [
        {
            _id:'1',
            name:'PS5',
            category:'Console',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name:'Pad1',
            category:'Pad',
            image: '/images/p1.jpg',
            price: 60,
            countInStock: 20,
            brand: 'Nike',
            rating: 2,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name:'Pad2',
            category:'Pad',
            image: '/images/p1.jpg',
            price: 60,
            countInStock: 0,
            brand: 'Nike',
            rating: 5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'4',
            name:'Cord',
            category:'Gadet',
            image: '/images/p1.jpg',
            price: 10,
            countInStock: 0,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name:'PS5',
            category:'console',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 100,
            brand: 'Nike',
            rating: 1,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};

export default data;